### ISSUE TITLE
Downloaded options no longer available

### ISSUE THREAD

**Issue by Tverous** [HCIILAB/SCUT_TKH_MTH_Datasets_Release#1]
As title.

The datasets are no longer exist in the referral link.

**Comment by WeihongM** [comment]
Hello, @Tverous 
Extended dataset version is shown in this link [TKH_MTH2200_Datasets_Release](https://github.com/HCIILAB/TKH_MTH2200_Datasets_Release)

**Comment by Tverous** [comment]
@WeihongM 

Thanks for all your hard work it is much appreciated!
